configure: - added check whether the bison GLR parser can actually be used, and suggest an   upgrade to at least version 1.875a if it cannot be used; due to a bug in an   old version of bison (1.875) which is standard on some Linux systems   (strangely enough), newer versions of gcc (4.0) generated errors   (noticed by Frank) - bugfix: errors after failed checks of the bison %glr-parser option and C99   were not displayed on a new line
test.y:
- added code to reproduce the bison bug

gsparser.y:
- removed obsolete declarations
- bugfix: in the previous renaming of the formats %t to %T for printing of
  ATerm's, this file was forgotten


git-svn-id: https://svn.win.tue.nl/repos/MCRL2/trunk@700 21252fe5-60e8-0310-8ff0-c1ae1001594e

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -722,13 +722,13 @@ echo X"$0" |
   	  /^X\(\/\).*/{ s//\1/; q; }
   	  s/.*/./; q'`
   srcdir=$ac_confdir
-  if test ! -r "$srcdir/$ac_unique_file"; then
+  if test ! -r $srcdir/$ac_unique_file; then
     srcdir=..
   fi
 else
   ac_srcdir_defaulted=no
 fi
-if test ! -r "$srcdir/$ac_unique_file"; then
+if test ! -r $srcdir/$ac_unique_file; then
   if test "$ac_srcdir_defaulted" = yes; then
     { echo "$as_me: error: cannot find sources ($ac_unique_file) in $ac_confdir or .." >&2
    { (exit 1); exit 1; }; }
@@ -737,7 +737,7 @@ if test ! -r "$srcdir/$ac_unique_file"; then
    { (exit 1); exit 1; }; }
   fi
 fi
-(cd $srcdir && test -r "./$ac_unique_file") 2>/dev/null ||
+(cd $srcdir && test -r ./$ac_unique_file) 2>/dev/null ||
   { echo "$as_me: error: sources are in $srcdir, but \`cd $srcdir' does not work" >&2
    { (exit 1); exit 1; }; }
 srcdir=`echo "$srcdir" | sed 's%\([^\\/]\)[\\/]*$%\1%'`
@@ -4016,8 +4016,27 @@ if $BISON test.y -o/dev/null &> /dev/null; then
   echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6;
 else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
   { { echo "$as_me:$LINENO: error: bison option %glr-parser not available" >&5
 echo "$as_me: error: bison option %glr-parser not available" >&2;}
+   { (exit 1); exit 1; }; };
+fi
+echo "$as_me:$LINENO: checking whether bison GLR parser can be used" >&5
+echo $ECHO_N "checking whether bison GLR parser can be used... $ECHO_C" >&6
+$BISON test.y -o test.c
+if $CC -c test.c &> /dev/null; then
+  glr_usable="yes"
+fi
+rm -f test.c
+if test $glr_usable; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6;
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+  { { echo "$as_me:$LINENO: error: bison GLR parser cannot be used with the $CC compiler; please upgrade to bison 1.875a or later" >&5
+echo "$as_me: error: bison GLR parser cannot be used with the $CC compiler; please upgrade to bison 1.875a or later" >&2;}
    { (exit 1); exit 1; }; };
 fi
 
@@ -4077,7 +4096,9 @@ echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
 ( exit $ac_status )
-{ { echo "$as_me:$LINENO: error: C99 standard not supported" >&5
+echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+  { { echo "$as_me:$LINENO: error: C99 standard not supported" >&5
 echo "$as_me: error: C99 standard not supported" >&2;}
    { (exit 1); exit 1; }; }
 
